/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import bd.MarcaDAO;
import bd.CafeDAO;
import entidades.Marca;
import entidades.Produto;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson, Emile, Gustavo, Maira
 */
public class FrameCafe extends javax.swing.JFrame {

    private JFrame origem;
    private MarcaDAO marcaDao;
    private CafeDAO produtoDao;
    /**
     * Creates new form FrameProdutos
     */
    public FrameCafe(JFrame origem) {
        initComponents();
        this.origem = origem;
        marcaDao = new MarcaDAO();
        produtoDao = new CafeDAO();
        cbMarcas.removeAllItems();
        LinkedList<Marca> lista = marcaDao.busca();
        if(lista!=null){
        for (Marca m: lista) {
            cbMarcas.addItem(m.getCodMarca() + " - " + m.getNomeMarca());
        }    }  
    }
    
    private void atualizaCbMarcas(){
        cbMarcas.removeAllItems();
        LinkedList<Marca> lista = marcaDao.busca();
        if(lista!=null){
        for (Marca m: lista) {
            cbMarcas.addItem(m.getCodMarca() + " - " + m.getNomeMarca());
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        cbMarcas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        AlterarCafe = new javax.swing.JLabel();
        InserirCafe = new javax.swing.JLabel();
        ExcluirCafe = new javax.swing.JLabel();
        ConsultarCafe = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VoltarCidade = new javax.swing.JLabel();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Café"));

        jLabel1.setText("Código");

        jLabel2.setText("Descrição");

        jLabel3.setText("Preço");

        jLabel4.setText("Quantidade");

        jLabel5.setText("Proprieário");

        AlterarCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atualizar.png"))); // NOI18N
        AlterarCafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlterarCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlterarCafeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AlterarCafeMouseEntered(evt);
            }
        });

        InserirCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inserir.png"))); // NOI18N
        InserirCafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InserirCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirCafeMouseClicked(evt);
            }
        });

        ExcluirCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        ExcluirCafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExcluirCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirCafeMouseClicked(evt);
            }
        });

        ConsultarCafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/consultar.png"))); // NOI18N
        ConsultarCafe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultarCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarCafeMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadastrocafe.png"))); // NOI18N

        VoltarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/voltar.png"))); // NOI18N
        VoltarCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarCidadeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbMarcas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigo)
                    .addComponent(txtDescricao))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(InserirCafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExcluirCafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AlterarCafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ConsultarCafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VoltarCidade)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InserirCafe)
                    .addComponent(ExcluirCafe)
                    .addComponent(ConsultarCafe)
                    .addComponent(AlterarCafe)
                    .addComponent(VoltarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCodigo, txtDescricao, txtPreco, txtSaldo});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        origem.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowStateChanged

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        atualizaCbMarcas();
    }//GEN-LAST:event_formWindowGainedFocus

    private Produto leProduto(){
        int idProduto = Integer.parseInt(txtCodigo.getText());
        String descricao = txtDescricao.getText();
        float preco = Float.parseFloat(txtPreco.getText());
        float saldo = Float.parseFloat(txtSaldo.getText());
        String aux = cbMarcas.getSelectedItem().toString();
        String marcaStr[] = aux.split(" - ");
        int idMarca = Integer.parseInt(marcaStr[0]);
        Marca marca = marcaDao.busca(idMarca);
        Produto produto = new Produto();
        produto.setCodProduto(idProduto);
        produto.setDescricao(descricao);
        produto.setPreco(preco);
        produto.setSaldo(saldo);
        produto.setMarca(marca);
        return produto;
    }    public int getID(){
        int z = Integer.parseInt(txtCodigo.getText());
        return z;
    }
    private void AlterarCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarCafeMouseClicked
         Produto p = leProduto();
        produtoDao.alterar(p);
    }//GEN-LAST:event_AlterarCafeMouseClicked

    private void AlterarCafeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarCafeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarCafeMouseEntered

    private void InserirCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirCafeMouseClicked
      Produto produto = leProduto();
        produtoDao.inserir(produto);
        JOptionPane.showMessageDialog(this,"Inserido café, com sucesso!");
        limpa();
    }//GEN-LAST:event_InserirCafeMouseClicked

    private void ExcluirCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirCafeMouseClicked
        // TODO add your handling code here:
        produtoDao.excluir(getID());
    }//GEN-LAST:event_ExcluirCafeMouseClicked

    private void ConsultarCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarCafeMouseClicked
        // TODO add your handling code here:
        marcaDao.busca(getID());
        //exibe();
    }//GEN-LAST:event_ConsultarCafeMouseClicked

    private void VoltarCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarCidadeMouseClicked
        // TODO add your handling code here:
        origem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarCidadeMouseClicked

    public void limpa(){
        txtCodigo.setText("");
        txtDescricao.setText("");
        txtPreco.setText("");
        txtSaldo.setText("");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlterarCafe;
    private javax.swing.JLabel ConsultarCafe;
    private javax.swing.JLabel ExcluirCafe;
    private javax.swing.JLabel InserirCafe;
    private javax.swing.JLabel VoltarCidade;
    private javax.swing.JComboBox cbMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
