/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import bd.CidadeDAO;
import entidades.Cidade;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson, Emile, Gustavo, Maira
 */
public class FrameCidade extends javax.swing.JFrame {
    private CidadeDAO cidadeDAO;
    private javax.swing.JFrame origem;
    /**
     * Creates new form FrameCidade
     */
    public FrameCidade(javax.swing.JFrame origem) {
        initComponents();
        this.origem = origem;
        cidadeDAO = new CidadeDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        InserirCidade = new javax.swing.JLabel();
        ExcluirCidade = new javax.swing.JLabel();
        ConsultarCidade = new javax.swing.JLabel();
        AlterarCidade = new javax.swing.JLabel();
        VoltarCidade = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cidade"));

        jLabel1.setText("Nome");

        jLabel2.setText("Estado");

        jLabel3.setText("Código");

        txtCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodActionPerformed(evt);
            }
        });
        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
        });

        InserirCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inserir.png"))); // NOI18N
        InserirCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InserirCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirCidadeMouseClicked(evt);
            }
        });

        ExcluirCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        ExcluirCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExcluirCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirCidadeMouseClicked(evt);
            }
        });

        ConsultarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/consultar.png"))); // NOI18N
        ConsultarCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultarCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarCidadeMouseClicked(evt);
            }
        });

        AlterarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atualizar.png"))); // NOI18N
        AlterarCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlterarCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlterarCidadeMouseClicked(evt);
            }
        });

        VoltarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/voltar.png"))); // NOI18N
        VoltarCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarCidadeMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cidade.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(InserirCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ExcluirCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultarCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlterarCidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VoltarCidade)
                        .addContainerGap())))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCod, txtEstado, txtNome});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(InserirCidade)
                        .addComponent(ExcluirCidade)
                        .addComponent(ConsultarCidade)
                        .addComponent(AlterarCidade))
                    .addComponent(VoltarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public int getID() {
        int id = Integer.parseInt(txtCod.getText());
        
        return id;
        
    }
    public Cidade leCidade(){
        Cidade cidade = new Cidade();
        int z = Integer.parseInt(txtCod.getText());
        cidade.setCodCidade(z);
        cidade.setNome(txtNome.getText());
        cidade.setEstado(txtEstado.getText());
        return cidade;
    
    }
    
    public void exibeCidade(Cidade cidade){
        txtCod.setText(String.valueOf(cidade.getCodCidade()));
        txtNome.setText(cidade.getNome());
        txtEstado.setText(cidade.getEstado());
        
        }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        origem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void InserirCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirCidadeMouseClicked
        // TODO add your handling code here:
            Cidade cidade = new Cidade();
        int z = Integer.parseInt(txtCod.getText());
        cidade.setCodCidade(z);
        cidade.setNome(txtNome.getText());
        cidade.setEstado(txtEstado.getText());
       
       Cidade c = cidadeDAO.busca(getID());
        if (c == null) {
          cidadeDAO.inserir(cidade);
          JOptionPane.showMessageDialog(this,"Inserido cidade, com sucesso!");
          limpa();  
        }else{
         JOptionPane.showMessageDialog(this,"Codigo da Cidade já Existe!");
        }
       
       
    }//GEN-LAST:event_InserirCidadeMouseClicked

    private void ExcluirCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirCidadeMouseClicked
        // TODO add your handling code here:
         cidadeDAO.excluir(getID());
         JOptionPane.showMessageDialog(this,"Excluido cidade, com sucesso!");
         limpa();
         
    }//GEN-LAST:event_ExcluirCidadeMouseClicked

    private void ConsultarCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarCidadeMouseClicked
        // TODO add your handling code here:
         Cidade c = cidadeDAO.busca(getID());
        if (c == null) {
            JOptionPane.showMessageDialog(this,"Codigo da Cidade não Cadastrada!");
        }else{
         exibeCidade(c);
        }
    }//GEN-LAST:event_ConsultarCidadeMouseClicked

    private void AlterarCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarCidadeMouseClicked
        // TODO add your handling code here:
        Cidade c = leCidade();
        cidadeDAO.alterar(c);
        JOptionPane.showMessageDialog(this,"Atualizado cidade, com sucesso!");
        limpa();
    }//GEN-LAST:event_AlterarCidadeMouseClicked

    private void VoltarCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarCidadeMouseClicked
        // TODO add your handling code here:
           origem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarCidadeMouseClicked

    private void txtCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodActionPerformed

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        // TODO add your handling code here:
        txtEstado.setText("");
        txtNome.setText("");
    }//GEN-LAST:event_txtCodKeyPressed

   public void limpa(){
        txtCod.setText("");
        txtEstado.setText("");
        txtNome.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlterarCidade;
    private javax.swing.JLabel ConsultarCidade;
    private javax.swing.JLabel ExcluirCidade;
    private javax.swing.JLabel InserirCidade;
    private javax.swing.JLabel VoltarCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
