/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import bd.CidadeDAO;
import bd.ClienteDAO;
import entidades.Cidade;
import entidades.Cliente;
import entidades.Marca;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anderson, Emile, Gustavo, Maira
 */
public class FrameClientes extends javax.swing.JFrame {
    private JFrame origem;
    private CidadeDAO cidadeDAO;
    private ClienteDAO clienteDAO;
    
    /**
     * Creates new form Clientes
     */
    public FrameClientes(JFrame origem) {
        initComponents();
        this.origem = origem;
        cidadeDAO = new CidadeDAO();
        clienteDAO = new ClienteDAO();
        listaCidades();
    }
    
   
    
    private void listaCidades(){
        cbCidade.removeAllItems(); // limpa combo box
        LinkedList<Cidade> lista = cidadeDAO.busca();
        if(lista!=null){
        for (Cidade cid : lista) {
            cbCidade.addItem(cid.getCodCidade() + " - " + cid.getNome());
        }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        cbCidade = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        AlterarCliente = new javax.swing.JLabel();
        InserirCliente = new javax.swing.JLabel();
        ExcluirCliente = new javax.swing.JLabel();
        ConsultarCliente = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BuscarCodigoClientes = new javax.swing.JLabel();
        BuscarNomeClientes = new javax.swing.JLabel();
        VoltarCidade = new javax.swing.JLabel();

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Telefone");

        jLabel4.setText("Cidade");

        cbCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCidadeActionPerformed(evt);
            }
        });

        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Telefone", "Cidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCliente);

        AlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/atualizar.png"))); // NOI18N
        AlterarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlterarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlterarClienteMouseClicked(evt);
            }
        });

        InserirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/inserir.png"))); // NOI18N
        InserirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InserirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InserirClienteMouseClicked(evt);
            }
        });

        ExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancelar.png"))); // NOI18N
        ExcluirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExcluirCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirClienteMouseClicked(evt);
            }
        });

        ConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/consultar.png"))); // NOI18N
        ConsultarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConsultarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarClienteMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadastroclientes.png"))); // NOI18N

        BuscarCodigoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        BuscarCodigoClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        BuscarNomeClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        BuscarNomeClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        VoltarCidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/voltar.png"))); // NOI18N
        VoltarCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarCidadeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InserirCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExcluirCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AlterarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ConsultarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VoltarCidade)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefone)
                            .addComponent(cbCidade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BuscarNomeClientes)
                            .addComponent(BuscarCodigoClientes))
                        .addGap(24, 24, 24))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BuscarCodigoClientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(BuscarNomeClientes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(InserirCliente)
                        .addComponent(ExcluirCliente)
                        .addComponent(AlterarCliente)
                        .addComponent(ConsultarCliente))
                    .addComponent(VoltarCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCodigo, txtNome, txtTelefone});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        origem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        listaCidades();
    }//GEN-LAST:event_formWindowGainedFocus

    private void ConsultarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarClienteMouseClicked
        // TODO add your handling code here:
        LinkedList<Cliente> lista = clienteDAO.busca();
        DefaultTableModel modelo =
        (DefaultTableModel)tabelaCliente.getModel();
        modelo.setNumRows(lista.size());

        for (int i = 0; i < lista.size(); i++) {
            Cliente c = lista.get(i);
            tabelaCliente.setValueAt(c.getCodCliente(), i, 0);
            tabelaCliente.setValueAt(c.getNome(),i,1);
            tabelaCliente.setValueAt(c.getTelefone(),i,2);
            Cidade cid = c.getCidade();
            tabelaCliente.setValueAt(cid.getNome(),i,3);
        }
    }//GEN-LAST:event_ConsultarClienteMouseClicked

    private void ExcluirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirClienteMouseClicked
        // TODO add your handling code here:
        clienteDAO.excluir(getID());
    }//GEN-LAST:event_ExcluirClienteMouseClicked

    private void InserirClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InserirClienteMouseClicked
        Cliente cliente = leCliente();
        clienteDAO.inserir(cliente);
        JOptionPane.showMessageDialog(this,"Inserido cliente, com sucesso!");
        limpa();
    }//GEN-LAST:event_InserirClienteMouseClicked

    private void AlterarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterarClienteMouseClicked
        // TODO add your handling code here:
        Cliente c = leCliente();
        clienteDAO.alterar(c);
    }//GEN-LAST:event_AlterarClienteMouseClicked

    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
        // TODO add your handling code here:
        int linha = tabelaCliente.getSelectedRow();
        JOptionPane.showMessageDialog(null, "Linha " + linha);
        int codCliente =(Integer) tabelaCliente.getValueAt(linha, 0);
        Cliente cli = clienteDAO.busca(codCliente);
        txtNome.setText(cli.getNome());
        txtTelefone.setText(cli.getTelefone());
        //converter para Texto o CodCliente ! txtCodigo.setText(cli.getCodCliente());

    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void cbCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCidadeActionPerformed

    private void VoltarCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarCidadeMouseClicked
        // TODO add your handling code here:
        origem.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VoltarCidadeMouseClicked
        public int getID(){
        int id = Integer.parseInt(txtCodigo.getText());
        return id;
    }
    
    private Cliente leCliente(){
        Cliente cliente = new Cliente();
        int codigo = Integer.parseInt(txtCodigo.getText());
        String nome = txtNome.getText();
        String telefone = txtTelefone.getText();
        String cidadeStr = cbCidade.getSelectedItem().toString();
        String cidadeVet[] = cidadeStr.split(" - ");
        int cidadeCod = Integer.parseInt(cidadeVet[0]);
        Cidade cidade = cidadeDAO.busca(cidadeCod);
        
        cliente.setCodCliente(codigo);
        cliente.setTelefone(telefone);
        cliente.setNome(nome);
        cliente.setCidade(cidade);
        return cliente;
    }
            
  public void limpa(){
     txtCodigo.setText("");
     txtNome.setText("");
     txtTelefone.setText("");
     cbCidade.setToolTipText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlterarCliente;
    private javax.swing.JLabel BuscarCodigoClientes;
    private javax.swing.JLabel BuscarNomeClientes;
    private javax.swing.JLabel ConsultarCliente;
    private javax.swing.JLabel ExcluirCliente;
    private javax.swing.JLabel InserirCliente;
    private javax.swing.JLabel VoltarCidade;
    private javax.swing.JComboBox cbCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCliente;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
