/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import java.awt.event.ActionEvent;
import java.lang.reflect.Method;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson, Emile, Gustavo, Maira
 */
public class Main extends javax.swing.JFrame {
    private FrameCidade frameCidade;
    private FrameClientes frameCliente;
    private FrameProp frameMarcas;
    private FrameCafe frameProdutos;
    private FrameVendas frameVendas;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        frameCidade = new FrameCidade(this);
        frameCliente = new FrameClientes(this);
        frameProdutos = new FrameCafe(this);
        frameVendas = new FrameVendas(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        MainVenda = new javax.swing.JLabel();
        MainProprietario = new javax.swing.JLabel();
        MainClientes = new javax.swing.JLabel();
        MainCidades = new javax.swing.JLabel();
        MainCafé = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(179, 221, 201));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        MainVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/venda.png"))); // NOI18N
        MainVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainVendaMouseClicked(evt);
            }
        });

        MainProprietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/proprietariobotao.png"))); // NOI18N
        MainProprietario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainProprietario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainProprietarioMouseClicked(evt);
            }
        });

        MainClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clientes.png"))); // NOI18N
        MainClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainClientesMouseClicked(evt);
            }
        });

        MainCidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cidades inicio.png"))); // NOI18N
        MainCidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainCidadesMouseClicked(evt);
            }
        });

        MainCafé.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cafe.png"))); // NOI18N
        MainCafé.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MainCafé.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainCaféMouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/armazemdecafe.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pergumta.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MainCidades, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MainProprietario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MainCafé, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MainVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MainClientes, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(215, 215, 215)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(MainCidades)
                        .addGap(18, 18, 18)
                        .addComponent(MainClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MainProprietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MainCafé)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MainVenda)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MainVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainVendaMouseClicked
        // TODO add your handling code here:
        frameVendas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MainVendaMouseClicked

    private void MainCaféMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainCaféMouseClicked
        // TODO add your handling code here:
        frameProdutos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MainCaféMouseClicked

    private void MainProprietarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainProprietarioMouseClicked
        // TODO add your handling code here:
        frameMarcas = new FrameProp(this);
        frameMarcas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MainProprietarioMouseClicked

   
    
    
    private void MainClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainClientesMouseClicked
        // TODO add your handling code here:
         frameCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MainClientesMouseClicked

    private void MainCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainCidadesMouseClicked
        // TODO add your handling code here:
        frameCidade.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MainCidadesMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
          openURL("http://www.cetcaf.com.br/apostila%20agregacao%20valor%20-%20rev%20jun-2011.pdf");
    }//GEN-LAST:event_jLabel1MouseClicked

         
 
    public void openURL(String url)     
    {     
        String osName = System.getProperty("os.name");     
        try     
        {     
            if (osName.startsWith("Mac OS"))     
            {     
                Class fileMgr = Class.forName("com.apple.eio.FileManager");     
                Method openURL = fileMgr.getDeclaredMethod("openURL",     
                    new Class[] {String.class});     
                openURL.invoke(null, new Object[] {url});     
            }     
            else if (osName.startsWith("Windows"))     
                Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + url);     
            else     
            { //assume Unix or Linux     
                String[] browsers = {     
                    "firefox", "opera", "konqueror", "epiphany", "mozilla", "netscape" };     
                String browser = null;     
                for (int count = 0; count < browsers.length && browser == null; count++)     
                    if (Runtime.getRuntime().exec(     
                    new String[] {"which", browsers[count]}).waitFor() == 0)     
                        browser = browsers[count];     
                if (browser == null)     
                    throw new Exception("Navegador não encontrado!");     
                else     
                    Runtime.getRuntime().exec(new String[] {browser, url});     
            }     
        }     
        catch (Exception e)     
        {     
            JOptionPane.showMessageDialog(null,  ":\n" + e.getLocalizedMessage());     
        }     
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainCafé;
    private javax.swing.JLabel MainCidades;
    private javax.swing.JLabel MainClientes;
    private javax.swing.JLabel MainProprietario;
    private javax.swing.JLabel MainVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
